
-------------------------------------------------------------------------------
			F C H  Construction
-------------------------------------------------------------------------------
Make what? Choose one of:
  make fch		Local program construction
  make install		Installation to BINDIR (normally /usr/local/bin)
  make clean		Cleanup of stale files
  make dist		Creates archive in /tmp
-------------------------------------------------------------------------------

Run
  BINDIR=/where/ever make install
to install into a different path.
